bikesharing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import fitur_2.urls as fitur_2

# individual views
from fitur_1 import views as fitur_1
from fitur_3 import views as fitur_3

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', fitur_1.landing_page),
    path('fitur_4/', include('fitur_4.urls')),
    # path('', include("fitur_1.urls")),
    path('__admin/', admin.site.urls),
    # path('', fitur_1.landing_page),
    path('', include(fitur_2,namespace='fitur_2')),
    path('', include("fitur_1.urls")),
    path('', include(fitur_2,namespace='fitur_2')),
    # path('', include("fitur_1.urls")),
    path('', include('fitur_3.urls')),
    # path('daftar_stasiun/', fitur_3.daftar_stasiun),
    # path('daftar_sepeda/', fitur_3.daftar_sepeda),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fitur_1/urls.py
from django.urls import path
from . import views
 

app_name = 'fitur_1'

urlpatterns = [
    path('', views.landing_page, name="landing"),
    path('laporan/', views.laporan, name="laporan"),
    path('transaksi/', views.riwayat, name="riwayat"),
    path('transaksi/topup/', views.topup, name="topup"),
    path('signin/', views.login, name="signin"),
    path('signup/', views.register, name="signup"),
    path('signout/', views.logout, name="signout"),
    path('saldo/', views.saldo, name="saldo"),
]

fitur_2/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from . import views

#url for app
app_name = "fitur_2"
urlpatterns = [
    url("TambahAcara/", views.DaftarAcara, name = "Daftar Acara"),
    url("ValueUpdateAcara/", views.ValueUpdateAcara, name = "Value Update Acara"),
    url("ValueAcara/", views.ValueDaftarAcara, name = "Value Acara"),
    url("TambahPenugasan/", views.DaftarPenugasan, name= "Daftar Penugasan"),
    url("ValueUpdatePenugasan/", views.ValueUpdatePenugasan, name = "Value Update Penugasan"),
    url("ValuePenugasan/", views.ValueDaftarPenugasan, name = "Value Penugasan"),
    url("UpdateAcara/", views.UpdateAcara, name = "Update Acara"),
    url("UpdatePenugasan/", views.UpdatePenugasan, name= "Update Penugasan"),
    url("Acara/", views.Acara, name="Acara"),
    url("HapusAcara/", views.HapusAcara, name="Hapus Acara"),
    url("Penugasan/", views.Penugasan, name="Penugasan")
]

fitur_3/urls.py
from django.urls import path
from . import views
 

app_name = "fitur_3"
urlpatterns = [
    path('tambah-stasiun', views.tambah_stasiun, name="tambah_stasiun"),
    path('tambah-sepeda', views.tambah_sepeda, name="tambah_sepeda"),
    path('update-stasiun', views.update_stasiun, name="update_stasiun"),
    path('update-sepeda', views.update_sepeda, name="update_sepeda"),
    path('daftar-stasiun', views.daftar_stasiun, name="daftar_stasiun"),
    path('daftar-stasiun/sorted-nama', views.stasiun_sortby_nama, name="stasiun_sortby_nama"),
    path('daftar-stasiun/sorted-alamat', views.stasiun_sortby_alamat, name="stasiun_sortby_alamat"),
    path('daftar-sepeda', views.daftar_sepeda, name="daftar_sepeda"),
    path('daftar-sepeda/tersedia', views.sepeda_tersedia, name="sepeda_tersedia"),
    path('daftar-sepeda/sorted-nomor', views.sepeda_sortby_nomor, name="sepeda_sortby_nomor"),
    path('daftar-sepeda/sorted-jenis', views.sepeda_sortby_jenis, name="sepeda_sortby_jenis"),
    path('daftar-sepeda/sorted-stasiun', views.sepeda_sortby_stasiun, name="sepeda_sortby_stasiun"),
    path('daftar-sepeda/sorted-penyumbang', views.sepeda_sortby_penyumbang, name="sepeda_sortby_penyumbang"),
]

fitur_4/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'fitur_4'

urlpatterns = [
    path('create_voucher/', views.create_voucher_fitur_4, name="create_voucher"),
    path('daftar_voucher/', views.daftar_voucher_fitur_4, name="daftar_voucher"),
    path('create_pinjaman/', views.create_pinjaman_fitur_4, name="create_pinjaman"),
    path('daftar_pinjaman/', views.daftar_pinjaman_fitur_4, name="daftar_pinjaman"),
]

templates/component/footer.html
<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item">
                        <a href="#">About</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Contact</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Terms of Use</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Privacy Policy</a>
                    </li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">&copy; Basis Data [A4] 2019.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-facebook fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-twitter-square fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <i class="fab fa-instagram fa-2x fa-fw"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/component/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="{% url 'fitur_1:landing'%}">Bikesharing</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" id="nav-list-left">
      {% if request.session.role == "anggota" %}
        <li class="nav-item">
                <a class="nav-link" href="{% url 'fitur_3:daftar_stasiun' %}">Daftar Stasiun</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'fitur_3:daftar_sepeda' %}">Daftar Sepeda</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Peminjaman
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'fitur_4:create_pinjaman' %}">Buat Peminjaman</a>
                    <a class="dropdown-item" href="{% url 'fitur_4:daftar_pinjaman' %}">Daftar Peminjaman</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Transaksi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'fitur_1:topup' %}">Top Up Sharebike Pay</a>
                    <a class="dropdown-item" href="{% url 'fitur_1:riwayat'%}">Riwayat Transaksi</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'fitur_2:Acara' %}">Daftar Acara</a>
            </li>
      {% elif request.session.role == "petugas" %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Penugasan
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'fitur_2:Daftar Penugasan' %}">Buat Penugasan</a>
                <a class="dropdown-item" href="{% url 'fitur_2:Penugasan' %}">Daftar Penugasan</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fitur_3:daftar_stasiun' %}">Daftar Stasiun</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fitur_3:daftar_sepeda' %}">Daftar Sepeda</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Acara
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'fitur_2:Daftar Acara' %}">Buat Acara</a>
                <a class="dropdown-item" href="{% url 'fitur_2:Acara' %}">Daftar Acara</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fitur_1:laporan' %}">Daftar Laporan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fitur_4:daftar_pinjaman' %}">Daftar Peminjaman</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Voucher
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'fitur_4:create_voucher' %}">Buat Voucher</a>
              <a class="dropdown-item" href="{% url 'fitur_4:daftar_voucher' %}">Daftar Voucher</a>
          </div>
      </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav ml-auto" id="nav-list-right">
      {% if request.session.role == "anggota" or request.session.role == "petugas" %}
        {% if request.session.role == "anggota" %}
          <li class="nav-item">
            <a class="btn btn-info text-white" id="saldo">. . .</a>
          </li>
        {% endif %}
        <li class="nav-item">
            <a class="btn btn-danger" href="{% url 'fitur_1:signout' %}">Sign Out</a>
        </li>
      {% else %}
        <li class="nav-item mx-1">
          <a class="btn btn-primary" href="{% url 'fitur_1:signin' %}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-success" href="{% url 'fitur_1:signup' %}">Sign Up</a>
        </li>
      {% endif %}

    </ul>
  </div>
  </div>
</nav>