bikesharing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import fitur_2.urls as fitur_2

# individual views
from fitur_1 import views as fitur_1
from fitur_3 import views as fitur_3

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', fitur_1.landing_page),
    path('fitur_4/', include('fitur_4.urls')),
    # path('', include("fitur_1.urls")),
    path('__admin/', admin.site.urls),
    # path('', fitur_1.landing_page),
    path('', include(fitur_2,namespace='fitur_2')),
    path('', include("fitur_1.urls")),
    path('', include(fitur_2,namespace='fitur_2')),
    # path('', include("fitur_1.urls")),
    path('', include('fitur_3.urls')),
    # path('daftar_stasiun/', fitur_3.daftar_stasiun),
    # path('daftar_sepeda/', fitur_3.daftar_sepeda),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fitur_1/urls.py
from django.urls import path
from . import views
 

app_name = 'fitur_1'

urlpatterns = [
    path('', views.landing_page, name="landing"),
    path('laporan/', views.laporan, name="laporan"),
    path('transaksi/', views.riwayat, name="riwayat"),
    path('transaksi/topup/', views.topup, name="topup"),
    path('signin/', views.login, name="signin"),
    path('signup/', views.register, name="signup"),
    path('signout/', views.logout, name="signout"),
    path('saldo/', views.saldo, name="saldo"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>
            {% block 'pagetitle' %}Bikesharing{% endblock 'pagetitle' %}
        </title>

        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom fonts for this template -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link href="{% static "vendor/simple-line-icons/css/simple-line-icons.css" %}"  rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- Custom styles for this template -->
        <link href="{% static "css/landing-page.min.css" %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

        {% block 'extreahead' %}
        {% endblock 'extreahead' %}
    </head>

    <body>

    <!-- Navigation -->
        {% include 'component/navbar.html' %}

        <!-- Content-->
        {% block 'content' %}
        {% endblock 'content' %}


        <!-- Footer -->
        {% include 'component/footer.html' %}

        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script>
            {% if request.session.role == "anggota" %}
                $.ajax(
                    {
                    url: "{% url 'fitur_1:saldo' %}",
                        datatype: 'json',
                    method:'POST',
                    success: function(result){
                        
                        $("#saldo").html(
                        "Saldo: "+ result.saldo
                        );
                    }
                    }
                )
            {% endif %}
        </script>
        {% block 'extrascript' %}
        {% endblock 'extrascript' %}
    </body>

</html>